language: csharp
solution: Csg.sln
install:
  - nuget restore Csg.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Csg.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Csg.Test/bin/Release/Csg.Test.dll
